export const projectsData = [
  {
    slug: 'vista-real-estate',
    title: 'Vista Real Estate',
    description: 'A premium property listing platform with Firebase authentication, an admin dashboard for verified agents, image uploads, and a dynamic property filtering engine.',
    overview: 'Vista Real Estate is designed to bridge the gap between property buyers and verified agents. The platform offers a seamless experience for browsing premium properties with advanced filtering options. Agents have a dedicated dashboard to manage their listings, upload high-quality images, and track inquiries.',
    challenge: 'The real estate market requires a high level of trust and visual appeal. The challenge was to build a platform that not only looks premium but also ensures that property data is handled securely and efficiently, allowing agents to manage listings without technical friction.',
    solution: 'I implemented a robust Firebase backend to handle user authentication and property data. The frontend is built with React, focusing on a clean, modern UI that highlights property imagery. The dynamic filtering engine allows users to easily find properties based on location, price, and features.',
    image: '/screenshots/vista-real-estate.png',
    gallery: ['/screenshots/vista-real-estate.png'],
    tags: ['Firebase', 'JS', 'HTML/CSS'],
    demo: 'https://vista-real-estate.onrender.com/',
    code: 'https://github.com/zannyphantom-13/Vista-real-estate',
    type: 'personal'
  },
  {
    slug: 'bella-cucina',
    title: 'Bella Cucina',
    description: 'An elegant, fully responsive Italian restaurant website with a dynamic menu, vibrant image gallery, and a built-in table reservation system.',
    overview: 'Bella Cucina brings the authentic Italian dining experience online. The website features a beautifully designed menu, a gallery showcasing their dishes, and an intuitive reservation system to help customers book tables easily.',
    challenge: 'Restaurant websites often struggle with outdated menus and clunky reservation systems. The goal was to create a fluid, mobile-first design that makes mouth-watering dishes the star of the show while simplifying the booking process.',
    solution: 'Built with HTML, CSS, and JavaScript, the site uses smooth scrolling and subtle animations to enhance the user experience. The reservation form is designed to be quick and user-friendly, directly notifying the restaurant staff.',
    image: '/screenshots/bella-cucina.png',
    gallery: ['/screenshots/bella-cucina.png'],
    tags: ['HTML', 'CSS', 'JavaScript'],
    demo: 'https://restaurant-website-kappa-jade.vercel.app/',
    code: 'https://github.com/zannyphantom-13/Restaurant-website',
    type: 'personal'
  },
  {
    slug: 'sharp-edge-barbershop',
    title: 'Sharp Edge Barbershop',
    description: 'An ultra-premium barbershop website with minimalist design, high-end typography, and a seamless live booking system interface.',
    overview: 'Sharp Edge Barbershop needed a digital presence that matched their premium in-shop experience. The website focuses on high-end aesthetics, clear service menus, and a straightforward booking process for clients.',
    challenge: 'Barbershop websites need to convert visitors into bookings quickly. The challenge was to balance a dark, sleek aesthetic with a highly functional booking interface that works flawlessly on mobile devices.',
    solution: 'I utilized a minimalist design language with stark contrasts and premium typography. The booking system interface was streamlined to require minimal steps, ensuring a frictionless experience for users booking their next haircut.',
    image: '/screenshots/sharp-edge-barbershop.png',
    gallery: ['/screenshots/sharp-edge-barbershop.png'],
    tags: ['HTML', 'CSS', 'JS'],
    demo: 'https://sharp-edge.onrender.com/',
    code: 'https://github.com/zannyphantom-13/barbershop-booking',
    type: 'personal'
  },
  {
    slug: 'common-finds-lts',
    title: 'Common Finds LTS',
    description: 'A robust local marketplace platform. Users can seamlessly buy, sell, and connect with people in their local neighbourhood with a personalized digital storefront.',
    overview: 'Common Finds LTS is a community-driven marketplace that empowers local residents to buy and sell items easily. It provides users with their own digital storefronts, fostering local commerce and connections.',
    challenge: 'Building a marketplace requires handling complex state management, user authentication, and real-time data updates for listings and messages, all while keeping the interface intuitive for non-technical users.',
    solution: 'I chose React for the frontend to manage the complex UI state and Firebase for the backend to handle real-time data and authentication. The result is a snappy, responsive platform where local transactions feel secure and straightforward.',
    image: '/screenshots/common-finds-lts.png',
    gallery: ['/screenshots/common-finds-lts.png'],
    tags: ['React', 'Firebase', 'Node.js'],
    demo: 'https://common-find-lts.onrender.com/',
    code: 'https://github.com/zannyphantom-13/common-find-lts',
    type: 'personal'
  },
  {
    slug: 'florida-roof-design',
    title: 'Florida Roof Design',
    description: 'A professional landing page for a Florida-based roofing company. Highlights specialized services, clear contact information, and an intuitive modern design.',
    overview: 'This landing page serves as the primary lead generation tool for Florida Roof Design. It clearly outlines their services, showcases past work, and provides immediate ways for potential clients to get in touch or request a quote.',
    challenge: 'Service businesses need to build trust instantly. The website had to look highly professional, load fast, and make the contact forms prominent without being overwhelming.',
    solution: 'Designed with clean HTML/CSS and enhanced with JS for interactivity, the site features clear calls-to-action, trust badges, and a layout that guides the user naturally towards the contact form.',
    image: '/screenshots/florida-roof-design.png',
    gallery: ['/screenshots/florida-roof-design.png'],
    tags: ['HTML', 'CSS', 'JS'],
    demo: 'https://floridaroofdesign.onrender.com/',
    code: 'https://github.com/zannyphantom-13/floridaroofdesign',
    type: 'personal'
  }
];

export const clientsData = [
  {
    slug: 'zealmart-world',
    name: 'Zealmart World',
    category: 'E-Commerce',
    description: 'A full-featured e-commerce platform for a Nigerian marketplace, with product listings, shopping cart, and order management.',
    overview: 'Zealmart World is a comprehensive e-commerce solution tailored for the Nigerian market. It supports diverse product categories, secure user accounts, and a streamlined checkout process.',
    challenge: 'The client needed a scalable platform that could handle a growing inventory while providing a smooth shopping experience on both mobile and desktop devices, even on slower network connections.',
    solution: 'I developed a highly optimized frontend paired with a robust backend to manage products and orders. The UI is designed to be intuitive, ensuring that users can easily find and purchase products.',
    url: 'https://www.zealmartworld.com.ng/',
    image: '/screenshots/zealmart-world.png',
    monogram: 'ZM',
    gradient: 'linear-gradient(135deg,#7c3aed,#06b6d4)',
    bg: 'linear-gradient(135deg,#0f1a2e,#162040)',
    gallery: ['/screenshots/zealmart-world.png'],
    type: 'client'
  },
  {
    slug: 'jd-good-hair',
    name: 'JD Good Hair',
    category: 'Beauty & Hair',
    description: 'A stylish salon and hair products website with product showcasing, booking flow, and a premium brand aesthetic for a Nigerian beauty business.',
    overview: 'JD Good Hair required a digital storefront that reflects their premium brand. The site showcases their high-quality hair products and integrates a booking flow for salon appointments.',
    challenge: 'Combining e-commerce functionality with a service booking system seamlessly, while maintaining a high-end, visually appealing design that resonates with their target audience.',
    solution: 'I created a visually rich interface with smooth transitions and high-quality imagery. The e-commerce and booking flows were carefully mapped out to ensure a cohesive user journey.',
    url: 'https://jd-goodhair.com.ng/',
    image: '/screenshots/jd-good-hair.png',
    monogram: 'JD',
    gradient: 'linear-gradient(135deg,#c084fc,#f472b6)',
    bg: 'linear-gradient(135deg,#1a0a1e,#2d0f2d)',
    gallery: ['/screenshots/jd-good-hair.png'],
    type: 'client'
  },
  {
    slug: 'the-electric-plug',
    name: 'The Electric Plug',
    category: 'Electronics & Tech',
    description: 'A modern electronics retail website featuring product catalogues, promotional banners, and easy contact options for a tech-focused brand.',
    overview: 'The Electric Plug is an online retail hub for the latest gadgets and electronics. The site features dynamic product displays, search functionality, and promotional spaces for new arrivals.',
    challenge: 'Displaying a large catalog of electronics without cluttering the interface. The site needed to look cutting-edge to match the tech products it sells.',
    solution: 'I implemented a clean, grid-based layout with advanced filtering options. The design uses tech-inspired colors and sharp typography to convey a modern feel.',
    url: 'https://www.theelectricplug.com/',
    image: '/screenshots/the-electric-plug.png',
    monogram: 'EP',
    gradient: 'linear-gradient(135deg,#4ade80,#06b6d4)',
    bg: 'linear-gradient(135deg,#0f1f0f,#1a3a1a)',
    gallery: ['/screenshots/the-electric-plug.png'],
    type: 'client'
  },
  {
    slug: 'lg-trusted-edge',
    name: 'LG Trusted Edge',
    category: 'Electronics Retail',
    description: 'An authorized LG products distributor website with product displays, trust badges, and a clean, professional layout that builds customer confidence.',
    overview: 'As an authorized LG distributor, this site needed to project trust and officiality. It features detailed product specifications, warranty information, and a professional layout.',
    challenge: 'Adhering to brand guidelines while creating a unique, engaging user experience that highlights the reliability of LG products and the distributor.',
    solution: 'The design leverages LG\'s corporate colors while introducing modern web design elements like subtle shadows and smooth hover states to create a trustworthy and engaging interface.',
    url: 'https://www.lgtrustedge.com.ng/',
    image: '/screenshots/lg-trusted-edge.png',
    monogram: 'LG',
    gradient: 'linear-gradient(135deg,#60a5fa,#a78bfa)',
    bg: 'linear-gradient(135deg,#0a0f2e,#1a1f4e)',
    gallery: ['/screenshots/lg-trusted-edge.png'],
    type: 'client'
  },
  {
    slug: 'skillift-services',
    name: 'SkilLift Services',
    category: 'Professional Services',
    description: 'A bilingual professional services platform with multilingual support, service showcasing, and a clean UI built for an international audience.',
    overview: 'SkilLift provides professional services to a diverse clientele. The website is bilingual, allowing users to switch languages seamlessly while browsing their service offerings.',
    challenge: 'Implementing a robust multilingual system without compromising page load speed or SEO, while keeping the design professional and accessible.',
    solution: 'I built a flexible language switching architecture that updates content dynamically. The UI is designed to accommodate different text lengths and formatting gracefully.',
    url: 'https://www.skiliftservices.com/en',
    image: '/screenshots/skillift-services.png',
    monogram: 'SL',
    gradient: 'linear-gradient(135deg,#fbbf24,#f97316)',
    bg: 'linear-gradient(135deg,#1a1000,#3a2800)',
    gallery: ['/screenshots/skillift-services.png'],
    type: 'client'
  },
  {
    slug: 'mac-christar-limited',
    name: 'Mac-Christar Limited',
    category: 'Corporate',
    description: 'A professional corporate website for an established Nigerian company, featuring service portfolios, company profile, and a strong brand identity online.',
    overview: 'Mac-Christar Limited needed a digital overhaul to reflect their established corporate presence. The site details their history, extensive service portfolio, and corporate governance.',
    challenge: 'Transforming dense corporate information into an engaging digital format that is easy to navigate and visually appealing to potential partners and clients.',
    solution: 'I utilized a structured, block-based design with ample white space. Clear typography and strategic use of brand colors help organize the content effectively.',
    url: 'https://www.mac-christarlimited.com/',
    image: '/screenshots/mac-christar-limited.png',
    monogram: 'MC',
    gradient: 'linear-gradient(135deg,#d97706,#92400e)',
    bg: 'linear-gradient(135deg,#0f0a00,#2a1f00)',
    gallery: ['/screenshots/mac-christar-limited.png'],
    type: 'client'
  },
  {
    slug: 'mayjay-electronics',
    name: 'Mayjay Electronics',
    category: 'Electronics & Retail',
    description: 'An electronics retail website for a Nigerian brand, featuring product showcasing, brand-forward design, and intuitive navigation for shoppers.',
    overview: 'Mayjay Electronics is a vibrant online store for consumer electronics. It focuses on deals, new arrivals, and providing an easy path to purchase.',
    challenge: 'Creating a unique identity in a crowded electronics retail space. The site needed to feel energetic and sales-driven while remaining easy to use.',
    solution: 'The design incorporates bold colors and prominent call-to-action buttons. The navigation is streamlined to help users find specific electronics categories quickly.',
    url: 'https://www.mayjay-electronics.com.ng/',
    image: '/screenshots/mayjay-electronics.png',
    monogram: 'MJ',
    gradient: 'linear-gradient(135deg,#c084fc,#7c3aed)',
    bg: 'linear-gradient(135deg,#100a1a,#1e1030)',
    gallery: ['/screenshots/mayjay-electronics.png'],
    type: 'client'
  }
];

export const allProjects = [...projectsData, ...clientsData];
